<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'time_zone' => '(UTC+04:30) Kabul'],
            ['name' => 'Albania', 'time_zone' => '(UTC+01:00) Tirane'],
            ['name' => 'Algeria', 'time_zone' => '(UTC+01:00) Algiers'],
            ['name' => 'Andorra', 'time_zone' => '(UTC+01:00) Andorra'],
            ['name' => 'Angola', 'time_zone' => '(UTC+01:00) Luanda'],
            ['name' => 'Antigua and Barbuda', 'time_zone' => '(UTC-04:00) Antigua'],
            ['name' => 'Argentina', 'time_zone' => '(UTC-03:00) Buenos Aires'],
            ['name' => 'Armenia', 'time_zone' => '(UTC+04:00) Yerevan'],
            ['name' => 'Australia', 'time_zone' => '(UTC+10:00) Sydney'],
            ['name' => 'Austria', 'time_zone' => '(UTC+01:00) Vienna'],
            ['name' => 'Azerbaijan', 'time_zone' => '(UTC+04:00) Baku'],
            ['name' => 'Bahamas', 'time_zone' => '(UTC-05:00) Nassau'],
            ['name' => 'Bahrain', 'time_zone' => '(UTC+03:00) Bahrain'],
            ['name' => 'Bangladesh', 'time_zone' => '(UTC+06:00) Dhaka'],
            ['name' => 'Barbados', 'time_zone' => '(UTC-04:00) Barbados'],
            ['name' => 'Belarus', 'time_zone' => '(UTC+03:00) Minsk'],
            ['name' => 'Belgium', 'time_zone' => '(UTC+01:00) Brussels'],
            ['name' => 'Belize', 'time_zone' => '(UTC-06:00) Belize'],
            ['name' => 'Benin', 'time_zone' => '(UTC+01:00) Porto-Novo'],
            ['name' => 'Bhutan', 'time_zone' => '(UTC+06:00) Thimphu'],
            ['name' => 'Bolivia', 'time_zone' => '(UTC-04:00) La Paz'],
            ['name' => 'Bosnia and Herzegovina', 'time_zone' => '(UTC+01:00) Sarajevo'],
            ['name' => 'Botswana', 'time_zone' => '(UTC+02:00) Gaborone'],
            ['name' => 'Brazil', 'time_zone' => '(UTC-03:00) Sao Paulo'],
            ['name' => 'Brunei', 'time_zone' => '(UTC+08:00) Brunei'],
            ['name' => 'Bulgaria', 'time_zone' => '(UTC+02:00) Sofia'],
            ['name' => 'Burkina Faso', 'time_zone' => '(UTC+00:00) Ouagadougou'],
            ['name' => 'Burundi', 'time_zone' => '(UTC+02:00) Bujumbura'],
            ['name' => 'Cambodia', 'time_zone' => '(UTC+07:00) Phnom Penh'],
            ['name' => 'Cameroon', 'time_zone' => '(UTC+01:00) Douala'],
            ['name' => 'Canada', 'time_zone' => '(UTC-05:00) Toronto'],
            ['name' => 'Cape Verde', 'time_zone' => '(UTC-01:00) Cape Verde'],
            ['name' => 'Central African Republic', 'time_zone' => '(UTC+01:00) Bangui'],
            ['name' => 'Chad', 'time_zone' => '(UTC+01:00) Ndjamena'],
            ['name' => 'Chile', 'time_zone' => '(UTC-03:00) Santiago'],
            ['name' => 'China', 'time_zone' => '(UTC+08:00) Shanghai'],
            ['name' => 'Colombia', 'time_zone' => '(UTC-05:00) Bogota'],
            ['name' => 'Comoros', 'time_zone' => '(UTC+03:00) Moroni'],
            ['name' => 'Congo', 'time_zone' => '(UTC+01:00) Brazzaville'],
            ['name' => 'Costa Rica', 'time_zone' => '(UTC-06:00) San Jose'],
            ['name' => 'Croatia', 'time_zone' => '(UTC+01:00) Zagreb'],
            ['name' => 'Cuba', 'time_zone' => '(UTC-05:00) Havana'],
            ['name' => 'Cyprus', 'time_zone' => '(UTC+02:00) Nicosia'],
            ['name' => 'Czech Republic', 'time_zone' => '(UTC+01:00) Prague'],
            ['name' => 'Denmark', 'time_zone' => '(UTC+01:00) Copenhagen'],
            ['name' => 'Djibouti', 'time_zone' => '(UTC+03:00) Djibouti'],
            ['name' => 'Dominica', 'time_zone' => '(UTC-04:00) Roseau'],
            ['name' => 'Dominican Republic', 'time_zone' => '(UTC-04:00) Santo Domingo'],
            ['name' => 'Ecuador', 'time_zone' => '(UTC-05:00) Quito'],
            ['name' => 'Egypt', 'time_zone' => '(UTC+02:00) Cairo'],
            ['name' => 'El Salvador', 'time_zone' => '(UTC-06:00) San Salvador'],
            ['name' => 'Equatorial Guinea', 'time_zone' => '(UTC+01:00) Malabo'],
            ['name' => 'Eritrea', 'time_zone' => '(UTC+03:00) Asmara'],
            ['name' => 'Estonia', 'time_zone' => '(UTC+02:00) Tallinn'],
            ['name' => 'Eswatini', 'time_zone' => '(UTC+02:00) Mbabane'],
            ['name' => 'Ethiopia', 'time_zone' => '(UTC+03:00) Addis Ababa'],
            ['name' => 'Fiji', 'time_zone' => '(UTC+12:00) Suva'],
            ['name' => 'Finland', 'time_zone' => '(UTC+02:00) Helsinki'],
            ['name' => 'France', 'time_zone' => '(UTC+01:00) Paris'],
            ['name' => 'Gabon', 'time_zone' => '(UTC+01:00) Libreville'],
            ['name' => 'Gambia', 'time_zone' => '(UTC+00:00) Banjul'],
            ['name' => 'Georgia', 'time_zone' => '(UTC+04:00) Tbilisi'],
            ['name' => 'Germany', 'time_zone' => '(UTC+01:00) Berlin'],
            ['name' => 'Ghana', 'time_zone' => '(UTC+00:00) Accra'],
            ['name' => 'Greece', 'time_zone' => '(UTC+02:00) Athens'],
            ['name' => 'Grenada', 'time_zone' => '(UTC-04:00) St. George\'s'],
            ['name' => 'Guatemala', 'time_zone' => '(UTC-06:00) Guatemala City'],
            ['name' => 'Guinea', 'time_zone' => '(UTC+00:00) Conakry'],
            ['name' => 'Guinea-Bissau', 'time_zone' => '(UTC+00:00) Bissau'],
            ['name' => 'Guyana', 'time_zone' => '(UTC-04:00) Georgetown'],
            ['name' => 'Haiti', 'time_zone' => '(UTC-05:00) Port-au-Prince'],
            ['name' => 'Honduras', 'time_zone' => '(UTC-06:00) Tegucigalpa'],
            ['name' => 'Hungary', 'time_zone' => '(UTC+01:00) Budapest'],
            ['name' => 'Iceland', 'time_zone' => '(UTC+00:00) Reykjavik'],
            ['name' => 'India', 'time_zone' => '(UTC+05:30) Kolkata'],
            ['name' => 'Indonesia', 'time_zone' => '(UTC+07:00) Jakarta'],
            ['name' => 'Iran', 'time_zone' => '(UTC+03:30) Tehran'],
            ['name' => 'Iraq', 'time_zone' => '(UTC+03:00) Baghdad'],
            ['name' => 'Ireland', 'time_zone' => '(UTC+00:00) Dublin'],
            ['name' => 'Israel', 'time_zone' => '(UTC+02:00) Jerusalem'],
            ['name' => 'Italy', 'time_zone' => '(UTC+01:00) Rome'],
            ['name' => 'Jamaica', 'time_zone' => '(UTC-05:00) Kingston'],
            ['name' => 'Japan', 'time_zone' => '(UTC+09:00) Tokyo'],
            ['name' => 'Jordan', 'time_zone' => '(UTC+02:00) Amman'],
            ['name' => 'Kazakhstan', 'time_zone' => '(UTC+06:00) Almaty'],
            ['name' => 'Kenya', 'time_zone' => '(UTC+03:00) Nairobi'],
            ['name' => 'Kiribati', 'time_zone' => '(UTC+12:00) Tarawa'],
            ['name' => 'Korea, North', 'time_zone' => '(UTC+09:00) Pyongyang'],
            ['name' => 'Korea, South', 'time_zone' => '(UTC+09:00) Seoul'],
            ['name' => 'Kuwait', 'time_zone' => '(UTC+03:00) Kuwait'],
            ['name' => 'Kyrgyzstan', 'time_zone' => '(UTC+06:00) Bishkek'],
            ['name' => 'Laos', 'time_zone' => '(UTC+07:00) Vientiane'],
            ['name' => 'Latvia', 'time_zone' => '(UTC+02:00) Riga'],
            ['name' => 'Lebanon', 'time_zone' => '(UTC+02:00) Beirut'],
            ['name' => 'Lesotho', 'time_zone' => '(UTC+02:00) Maseru'],
            ['name' => 'Liberia', 'time_zone' => '(UTC+00:00) Monrovia'],
            ['name' => 'Libya', 'time_zone' => '(UTC+02:00) Tripoli'],
            ['name' => 'Liechtenstein', 'time_zone' => '(UTC+01:00) Vaduz'],
            ['name' => 'Lithuania', 'time_zone' => '(UTC+02:00) Vilnius'],
            ['name' => 'Luxembourg', 'time_zone' => '(UTC+01:00) Luxembourg'],
            ['name' => 'Madagascar', 'time_zone' => '(UTC+03:00) Antananarivo'],
            ['name' => 'Malawi', 'time_zone' => '(UTC+02:00) Blantyre'],
            ['name' => 'Malaysia', 'time_zone' => '(UTC+08:00) Kuala Lumpur'],
            ['name' => 'Maldives', 'time_zone' => '(UTC+05:00) Male'],
            ['name' => 'Mali', 'time_zone' => '(UTC+00:00) Bamako'],
            ['name' => 'Malta', 'time_zone' => '(UTC+01:00) Valletta'],
            ['name' => 'Marshall Islands', 'time_zone' => '(UTC+12:00) Majuro'],
            ['name' => 'Mauritania', 'time_zone' => '(UTC+00:00) Nouakchott'],
            ['name' => 'Mauritius', 'time_zone' => '(UTC+04:00) Port Louis'],
            ['name' => 'Mexico', 'time_zone' => '(UTC-06:00) Mexico City'],
            ['name' => 'Micronesia', 'time_zone' => '(UTC+10:00) Palikir'],
            ['name' => 'Moldova', 'time_zone' => '(UTC+02:00) Chisinau'],
            ['name' => 'Monaco', 'time_zone' => '(UTC+01:00) Monaco'],
            ['name' => 'Mongolia', 'time_zone' => '(UTC+08:00) Ulaanbaatar'],
            ['name' => 'Montenegro', 'time_zone' => '(UTC+01:00) Podgorica'],
            ['name' => 'Morocco', 'time_zone' => '(UTC+00:00) Casablanca'],
            ['name' => 'Mozambique', 'time_zone' => '(UTC+02:00) Maputo'],
            ['name' => 'Myanmar', 'time_zone' => '(UTC+06:30) Yangon'],
            ['name' => 'Namibia', 'time_zone' => '(UTC+02:00) Windhoek'],
            ['name' => 'Nauru', 'time_zone' => '(UTC+12:00) Nauru'],
            ['name' => 'Nepal', 'time_zone' => '(UTC+05:45) Kathmandu'],
            ['name' => 'Netherlands', 'time_zone' => '(UTC+01:00) Amsterdam'],
            ['name' => 'New Zealand', 'time_zone' => '(UTC+12:00) Wellington'],
            ['name' => 'Nicaragua', 'time_zone' => '(UTC-06:00) Managua'],
            ['name' => 'Niger', 'time_zone' => '(UTC+01:00) Niamey'],
            ['name' => 'Nigeria', 'time_zone' => '(UTC+01:00) Lagos'],
            ['name' => 'Norway', 'time_zone' => '(UTC+01:00) Oslo'],
            ['name' => 'Oman', 'time_zone' => '(UTC+04:00) Muscat'],
            ['name' => 'Pakistan', 'time_zone' => '(UTC+05:00) Karachi'],
            ['name' => 'Palau', 'time_zone' => '(UTC+09:00) Koror'],
            ['name' => 'Panama', 'time_zone' => '(UTC-05:00) Panama City'],
            ['name' => 'Papua New Guinea', 'time_zone' => '(UTC+10:00) Port Moresby'],
            ['name' => 'Paraguay', 'time_zone' => '(UTC-04:00) Asuncion'],
            ['name' => 'Peru', 'time_zone' => '(UTC-05:00) Lima'],
            ['name' => 'Philippines', 'time_zone' => '(UTC+08:00) Manila'],
            ['name' => 'Poland', 'time_zone' => '(UTC+01:00) Warsaw'],
            ['name' => 'Portugal', 'time_zone' => '(UTC+00:00) Lisbon'],
            ['name' => 'Qatar', 'time_zone' => '(UTC+03:00) Doha'],
            ['name' => 'Romania', 'time_zone' => '(UTC+02:00) Bucharest'],
            ['name' => 'Russia', 'time_zone' => '(UTC+03:00) Moscow'],
            ['name' => 'Rwanda', 'time_zone' => '(UTC+02:00) Kigali'],
            ['name' => 'Saint Kitts and Nevis', 'time_zone' => '(UTC-04:00) Basseterre'],
            ['name' => 'Saint Lucia', 'time_zone' => '(UTC-04:00) Castries'],
            ['name' => 'Saint Vincent and the Grenadines', 'time_zone' => '(UTC-04:00) Kingstown'],
            ['name' => 'Samoa', 'time_zone' => '(UTC+13:00) Apia'],
            ['name' => 'San Marino', 'time_zone' => '(UTC+01:00) San Marino'],
            ['name' => 'Saudi Arabia', 'time_zone' => '(UTC+03:00) Riyadh'],
            ['name' => 'Senegal', 'time_zone' => '(UTC+00:00) Dakar'],
            ['name' => 'Serbia', 'time_zone' => '(UTC+01:00) Belgrade'],
            ['name' => 'Seychelles', 'time_zone' => '(UTC+04:00) Victoria'],
            ['name' => 'Sierra Leone', 'time_zone' => '(UTC+00:00) Freetown'],
            ['name' => 'Singapore', 'time_zone' => '(UTC+08:00) Singapore'],
            ['name' => 'Slovakia', 'time_zone' => '(UTC+01:00) Bratislava'],
            ['name' => 'Slovenia', 'time_zone' => '(UTC+01:00) Ljubljana'],
            ['name' => 'Solomon Islands', 'time_zone' => '(UTC+11:00) Honiara'],
            ['name' => 'Somalia', 'time_zone' => '(UTC+03:00) Mogadishu'],
            ['name' => 'South Africa', 'time_zone' => '(UTC+02:00) Johannesburg'],
            ['name' => 'Spain', 'time_zone' => '(UTC+01:00) Madrid'],
            ['name' => 'Sri Lanka', 'time_zone' => '(UTC+05:30) Colombo'],
            ['name' => 'Sudan', 'time_zone' => '(UTC+02:00) Khartoum'],
            ['name' => 'Suriname', 'time_zone' => '(UTC-03:00) Paramaribo'],
            ['name' => 'Sweden', 'time_zone' => '(UTC+01:00) Stockholm'],
            ['name' => 'Switzerland', 'time_zone' => '(UTC+01:00) Zurich'],
            ['name' => 'Syria', 'time_zone' => '(UTC+02:00) Damascus'],
            ['name' => 'Taiwan', 'time_zone' => '(UTC+08:00) Taipei'],
            ['name' => 'Tajikistan', 'time_zone' => '(UTC+05:00) Dushanbe'],
            ['name' => 'Tanzania', 'time_zone' => '(UTC+03:00) Dar es Salaam'],
            ['name' => 'Thailand', 'time_zone' => '(UTC+07:00) Bangkok'],
            ['name' => 'Togo', 'time_zone' => '(UTC+00:00) Lome'],
            ['name' => 'Tonga', 'time_zone' => '(UTC+13:00) Nuku\'alofa'],
            ['name' => 'Trinidad and Tobago', 'time_zone' => '(UTC-04:00) Port of Spain'],
            ['name' => 'Tunisia', 'time_zone' => '(UTC+01:00) Tunis'],
            ['name' => 'Turkey', 'time_zone' => '(UTC+03:00) Istanbul'],
            ['name' => 'Turkmenistan', 'time_zone' => '(UTC+05:00) Ashgabat'],
            ['name' => 'Tuvalu', 'time_zone' => '(UTC+12:00) Funafuti'],
            ['name' => 'Uganda', 'time_zone' => '(UTC+03:00) Kampala'],
            ['name' => 'Ukraine', 'time_zone' => '(UTC+02:00) Kyiv'],
            ['name' => 'United Arab Emirates', 'time_zone' => '(UTC+04:00) Dubai'],
            ['name' => 'United Kingdom', 'time_zone' => '(UTC+00:00) London'],
            ['name' => 'United States', 'time_zone' => '(UTC-05:00) New York'],
            ['name' => 'Uruguay', 'time_zone' => '(UTC-03:00) Montevideo'],
            ['name' => 'Uzbekistan', 'time_zone' => '(UTC+05:00) Tashkent'],
            ['name' => 'Vanuatu', 'time_zone' => '(UTC+11:00) Port Vila'],
            ['name' => 'Vatican City', 'time_zone' => '(UTC+01:00) Vatican City'],
            ['name' => 'Venezuela', 'time_zone' => '(UTC-04:00) Caracas'],
            ['name' => 'Vietnam', 'time_zone' => '(UTC+07:00) Hanoi'],
            ['name' => 'Yemen', 'time_zone' => '(UTC+03:00) Sana\'a'],
            ['name' => 'Zambia', 'time_zone' => '(UTC+02:00) Lusaka'],
            ['name' => 'Zimbabwe', 'time_zone' => '(UTC+02:00) Harare'],
        ];

        DB::table('countries')->insertOrIgnore($countries);
    }
}
